In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, r2_score

In [2]:
df_classification = pd.read_csv('heart_classification.csv')

In [3]:
df_classification.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
df_regression = pd.read_csv("Salary.csv")

In [5]:
df_regression.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [6]:
from KNN import KNNClassifier, KNNRegression

In [7]:
X_class = df_classification.iloc[:,:-1].values
y_class = df_classification.iloc[:,-1].values
X_reg = df_regression.iloc[:,:-1].values
y_reg = df_regression.iloc[:,-1].values

In [8]:
k_class = KNNClassifier()
k_reg = KNNRegression()

k_class.fit(X_class, y_class)
k_reg.fit(X_reg, y_reg)

y_class_pred = k_class.predict(X_class)
y_reg_pred = k_reg.predict(X_reg)

In [12]:
print(f"Classifier Accuracy: {accuracy_score(y_class, y_class_pred)*100:.2f} %")
print(f"Regressor Accuracy: {r2_score(y_reg, y_reg_pred)*100:.2f} %")

Classifier Accuracy: 75.91 %
Regressor Accuracy: 98.21 %